import { Router } from "express";
import suggestRouter from "./suggest";
import suggestionsRouter from "./suggestions";
import feedbackRouter from "./feedback";
import approveRouter from "./approve";
import skipRouter from "./skip";
import themeRouter from "./theme";
import settingsRouter from "./settings";
import transcribeRouter from "./transcribe";
import sendMessageRouter from "./send-message";
import leadStageRouter from "./lead-stage";
import correctionRouter from "./correction";
import scheduleTaskRouter from "./schedule-task";
import stageOptionsRouter from "./stage-options";
import parseTaskRouter from "./parse-task";
import botExcludeRouter from "./bot-exclude";
import userSettingsRouter from "./user-settings";
import responsibleUsersRouter from "./responsible-users";
import pipelinesRouter from "./pipelines";
import pushRouter from "./push";
import whoamiRouter from "./whoami";
import setTemperatureRouter from "./set-temperature";
import rescheduleTaskRouter from "./reschedule-task";
import noReplyNeededRouter from "./no-reply-needed";
import autopilotRouter from "./autopilot";
import budgetFilterRouter from "./budget-filter";
import aiSpendRouter from "./ai-spend";
import listingSubmissionsRouter from "./listing-submissions";
import listingIntakeRouter from "./listing-intake";
import brokerAgentRouter from "./broker-agent";
import reportRouter from "./report";
import autopilotReadinessRouter from "./autopilot-readiness";

const router = Router();

router.use(suggestRouter);
router.use(autopilotRouter);
router.use(autopilotReadinessRouter);
router.use(budgetFilterRouter);
router.use(aiSpendRouter);
router.use(suggestionsRouter);
router.use(feedbackRouter);
router.use(approveRouter);
router.use(skipRouter);
router.use(themeRouter);
router.use(settingsRouter);
router.use(transcribeRouter);
router.use(sendMessageRouter);
router.use(leadStageRouter);
router.use(correctionRouter);
router.use(scheduleTaskRouter);
router.use(stageOptionsRouter);
router.use(parseTaskRouter);
router.use(botExcludeRouter);
router.use(userSettingsRouter);
router.use(responsibleUsersRouter);
router.use(pipelinesRouter);
router.use(pushRouter);
router.use(whoamiRouter);
router.use(setTemperatureRouter);
router.use(rescheduleTaskRouter);
router.use(noReplyNeededRouter);
router.use(listingSubmissionsRouter);
router.use(listingIntakeRouter);
router.use(brokerAgentRouter);
router.use(reportRouter);

export default router;
