import { Router, type IRouter } from "express";
import healthRouter from "./health";
import publicRouter from "./public";
import amocrmWebhookRouter from "./amocrm-webhook";
import amocrmSyncStageRouter from "./amocrm-sync-stage";
import downloadRouter from "./download";
import dashboardRouter from "./dashboard";
import uploadRouter from "./upload";
import bulkImportRouter from "./admin/bulk-import";
import refreshPushRouter from "./admin/refresh-push";
import reclassifyStagesRouter from "./admin/reclassify-stages";
import forcePushRouter from "./admin/force-push";
import syncStagesBulkRouter from "./admin/sync-stages-bulk";
import amoOauthRouter from "./admin/amo-oauth";
import pushStagesRouter from "./admin/push-stages";
import queueQualificationRouter from "./admin/queue-qualification";
import smartRequeueRouter from "./admin/smart-requeue";
import amoInstallRouter from "./amo-install";
import analyticsRouter from "./analytics";
import amocrmContactEventRouter from "./amocrm-contact-event";
import amoFullImportRouter from "./admin/amo-full-import";
import runSchedulerRouter from "./admin/run-scheduler";
import bulkPushActiveStagesRouter from "./admin/bulk-push-active-stages";
import syncLiveNowRouter from "./admin/sync-live-now";
import backfillAmoCreatedAtRouter from "./admin/backfill-amo-created-at";
import debugAmojoRouter from "./debug-amojo";
import debugTalksRouter from "./debug-talks";
import deployWebhookRouter from "./deploy-webhook";
import pipelinesRouter from "./admin/pipelines";
import leadFieldsRouter from "./admin/lead-fields";
import backfillListingFieldsRouter from "./admin/backfill-listing-fields";
import requalifyDraftsRouter from "./admin/requalify-drafts";
import syncTimelineRouter from "./admin/sync-timeline";
import correctionsDedupeRouter from "./admin/corrections-dedupe";
import amocrmChatWebhookRouter from "./amocrm-chat-webhook";
import sendChatMessageRouter from "./public/send-chat-message";
import { adminAuth } from "../lib/admin-auth";

const router: IRouter = Router();

// Guard internal /admin/* and /debug/* endpoints (see lib/admin-auth.ts). Must be
// first so it runs before any admin router. amoCRM webhooks, /public (extension),
// health, downloads, dashboard and the amo-oauth callback are NOT affected.
router.use(adminAuth);

router.use(healthRouter);
router.use("/public", publicRouter);
router.use(amocrmWebhookRouter);
router.use(amocrmSyncStageRouter);
router.use(amocrmContactEventRouter);
router.use(downloadRouter);
router.use(dashboardRouter);
router.use(uploadRouter);
router.use(bulkImportRouter);
router.use(refreshPushRouter);
router.use(reclassifyStagesRouter);
router.use(forcePushRouter);
router.use(syncStagesBulkRouter);
router.use(correctionsDedupeRouter);
router.use(amoOauthRouter);
router.use(pushStagesRouter);
router.use(queueQualificationRouter);
router.use(smartRequeueRouter);
router.use(amoInstallRouter);
router.use(analyticsRouter);
router.use(amoFullImportRouter);
router.use(runSchedulerRouter);
router.use(bulkPushActiveStagesRouter);
router.use(syncLiveNowRouter);
router.use(backfillAmoCreatedAtRouter);
router.use(debugAmojoRouter);
router.use(debugTalksRouter);
router.use(deployWebhookRouter);
router.use(pipelinesRouter);
router.use(leadFieldsRouter);
router.use(backfillListingFieldsRouter);
router.use(requalifyDraftsRouter);
router.use(syncTimelineRouter);
router.use(amocrmChatWebhookRouter);
router.use(sendChatMessageRouter);

export default router;
